### ISSUE TITLE
which version of husky does it need

### ISSUE THREAD

**Issue by heylypp** [lorenzoferrini/ins_uwb_positioning#1]
```
No such file or directory:  /src/husky/husky_description/urdf/accessories/kinect_camera.urdf.xacro
```
And the husky model is not the same as yours.
which version of husky does it need？

![image](https://user-images.githubusercontent.com/16957782/102996688-8117e000-455e-11eb-9e8f-f4d70966c939.png)
![image](https://user-images.githubusercontent.com/16957782/102996809-aefd2480-455e-11eb-869d-b22528dbe5c3.png)

**Comment by lorenzoferrini** [comment]
The robot model used in this simulation is not the one used in the paper and it is indeed an husky model just as the one you posted. 
For what concerns the error the husky_description package was updated and the kinect_camera sensor removed. I just pushed a quick fix.

**Comment by heylypp** [comment]
Thanks！！！
